import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

import '../model/product_model.dart';

class ApiServices {
  static const String baseUrl = 'dummyjson.com';

  static int _page1 = 0;
  static int get page1 => _page1 += 1;

  static int _page2 = 0;
  static int get page2 => _page2 += 1;

  static void resetSearchPage() {
    _page2 = 0;
  }

  static Future<List<Products>?> getAllProducts() async {
    int limit = 10;
    int skip = (page1 - 1) * limit;

    var url =
        Uri.https(baseUrl, '/products', {'limit': '$limit', 'skip': '$skip'});

    var response = await http.get(url);
    if (response.statusCode == 200) {
      String jsonString = response.body;
      var res = autogeneratedFromJson(jsonString);
      return res.products;
    } else {
      debugPrint('Request failed with status: ${response.statusCode}');
      return null;
    }
  }

  static Future<List<Products>?> getProducts(String search) async {
    int limit = 6;
    int skip = (page2 - 1) * limit;

    var url = Uri.https(
      baseUrl,
      '/products/search',
      {'q': search, 'limit': '$limit', 'skip': '$skip'},
    );

    var response = await http.get(url);
    if (response.statusCode == 200) {
      String jsonString = response.body;
      var res = autogeneratedFromJson(jsonString);
      return res.products;
    } else {
      debugPrint('Request failed with status: ${response.statusCode}');
      return null;
    }
  }
}
